name: Build and deploy TheoreticalAstrophysicsGroup site to charon

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1.217.0
      with:
        ruby-version: '3.2.2'
    - name: Install dependencies
      run: bundle install
    - name: Build
      run: bundle exec jekyll build
    - name: Rsync deploy
      uses: Burnett01/rsync-deployments@7.0.2
      with:
        switches: -vizr
        legacy_allow_rsa_hostkeys: "true"
        path: _site/
        remote_path: ${{ secrets.DEPLOY_PATH }}
        remote_host: ${{ secrets.DEPLOY_HOST }}
        remote_port: ${{ secrets.DEPLOY_PORT }}
        remote_user: ${{ secrets.DEPLOY_USER }}
        remote_key: ${{ secrets.DEPLOY_KEY }}
