name: Build and deploy TheoreticalAstrophysicsGroup site to charon

on:
  push:
    branches: [ source ]
  pull_request:
    branches: [ source ]

  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: rsync deployments
      uses: burnett01/rsync-deployments@v8
      with:
        switches: -vizr
        legacy_allow_rsa_hostkeys: "true"
        path: _site/
        remote_path: ${{ secrets.REMOTE_PATH }} # ex: /var/www/html/
        remote_host: ${{ secrets.REMOTE_HOST }} # ex: example.com
        remote_port: ${{ secrets.REMOTE_PORT }} # ex: 22
        remote_user: ${{ secrets.REMOTE_USER }} # ex: ubuntu
        remote_key: ${{ secrets.REMOTE_PRIVATE_KEY }}
        remote_key_pass: ${{ secrets.REMOTE_PRIVATE_KEY_PASS }}
#    - name: Set up Ruby
#      uses: ruby/setup-ruby@v1.217.0
#      with:
#        ruby-version: '3.2.2'
#    - name: Install dependencies
#      run: bundle install
#    - name: Build
#      run: bundle exec jekyll build --future
